import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { MetaMaskUIProvider } from '@metamask/sdk-react-ui';
import SDKContainer from "@/components/SDKContainer";


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning={true}>
      <body className={inter.className}>
          <SDKContainer>
              {children}
          </SDKContainer>
      </body>
    </html>
  )
}
